openapi: 3.0.0
info:
  title: Movies Watchlist API
  version: 1.0.0
  description: An API for an ecommerce platform.
servers:
  - url: http://localhost:3000
    description: Local dev
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token obtained from login or refresh endpoints
  schemas:
    $ref: './components/schemas.yaml'
security:
  - bearerAuth: []
paths:
  /auth/register:
    $ref: './paths/auth.yaml#//api/v1/auth/register'
  /auth/login:
    $ref: './paths/auth.yaml#//api/v1/auth/login'
  /auth/refresh:
    $ref: './paths/auth.yaml#//api/v1/auth/refresh'
  /auth/logout:
    $ref: './paths/auth.yaml#//api/v1/logout'
  /auth/me:
    $ref: './paths/auth.yaml#//api/v1/me'
    